environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain beta
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  - rustup component add clippy

build: false

test_script:
  - cargo clippy
  - cargo build --target %TARGET%
  - cargo test --target %TARGET%
