[package]
name = "tokio-timer"
version = "0.2.3"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://github.com/tokio-rs/tokio"
documentation = "https://docs.rs/tokio-timer"
description = """
Timer facilities for Tokio
"""

[dependencies]
futures = "0.1.19"
tokio-executor = { version = "0.1.1", path = "../tokio-executor" }

[dev-dependencies]
rand = "0.4.2"
