version: 2.1        
jobs:
  test-arm:
    machine:
      image: default
    resource_class: arm.medium
    environment:
      # Change to pin rust version
      RUST_STABLE: stable
    steps:
      - checkout
      - run:
          name: Install Rust
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh
            chmod +x rustup.sh
            ./rustup.sh -y --default-toolchain $RUST_STABLE
            source "$HOME"/.cargo/env
      # Only run Tokio tests
      - run: cargo test --all-features -p tokio

workflows:
  ci:
    jobs:
      - test-arm
