[package]
name = "tokio-udp"

# When releasing to crates.io:
# - Update html_root_url.
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tokio-udp/0.1"
description = """
UDP bindings for tokio.
"""
categories = ["asynchronous"]

[dependencies]
tokio-io = { version = "0.1.6", path = "../tokio-io" }
tokio-reactor = { version = "0.1.1", path = "../tokio-reactor" }
bytes = "0.4"
mio = "0.6.14"
log = "0.4"
futures = "0.1.19"

# Futures 0.2 integration
futures2 = { version = "0.1", path = "../futures2", optional = true }

[dev-dependencies]
env_logger = { version = "0.4", default-features = false }

[features]
unstable-futures = [
  "futures2",
  "tokio-reactor/unstable-futures",
]
default = []
