[package]
name = "tokio-udp"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.2.x" git tag.
version = "0.2.0"
edition = "2018"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
documentation = "https://docs.rs/tokio-udp/0.1.3/tokio_udp"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://tokio.rs"
description = """
UDP bindings for tokio.
"""
categories = ["asynchronous"]
publish = false

[dependencies]
# tokio-codec = { version = "0.2.0", path = "../tokio-codec" }
# tokio-io = { version = "0.2.0", path = "../tokio-io" }
tokio-reactor = { version = "0.2.0", path = "../tokio-reactor" }
# bytes = "0.4"
mio = "0.6.14"
log = "0.4"
futures-core-preview = "= 0.3.0-alpha.17"
futures-util-preview = "= 0.3.0-alpha.17"

[dev-dependencies]
env_logger = { version = "0.5", default-features = false }
tokio = { version = "0.2.0", path = "../tokio", default-features = false, features = ["rt-full"] }
