[package]
name = "tokio-udp"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
# - Update CHANGELOG.md.
# - Create "v0.2.x" git tag.
version = "0.2.0-alpha.1"
edition = "2018"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
documentation = "https://docs.rs/tokio-udp/0.2.0-alpha.1/tokio_udp"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://tokio.rs"
description = """
UDP bindings for tokio.
"""
categories = ["asynchronous"]

[dependencies]
tokio-codec = { version = "=0.2.0-alpha.1", path = "../tokio-codec" }
# tokio-io = { version = "0.2.0", path = "../tokio-io" }
tokio-reactor = { version = "=0.2.0-alpha.1", path = "../tokio-reactor" }

bytes = "0.4.12"
mio = "0.6.14"
log = "0.4"
futures-core-preview = "=0.3.0-alpha.18"
futures-util-preview = "=0.3.0-alpha.18"
futures-sink-preview = "=0.3.0-alpha.18"

[dev-dependencies]
tokio = { version = "=0.2.0-alpha.1", path = "../tokio", default-features = false, features = ["rt-full"] }

env_logger = { version = "0.6", default-features = false }
