name: benchmark
on:
  push:
    branches:
      - master

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    env:
      BENCHER_API_TOKEN: ${{ secrets.BENCHER_API_TOKEN }}
    strategy:
      matrix:
        bench:
          - ct_spawn
    steps:
      - uses: actions/checkout@v5

      - run: sudo apt-get update && sudo apt-get install -y valgrind

      - uses: taiki-e/install-action@cargo-binstall
      - name: Install gungraun-runner
        run: |
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "gungraun").version' |\
            tr -d '"'
          )
          cargo binstall --no-confirm gungraun-runner --version $version

      - uses: bencherdev/bencher@main
      - name: Run Bencher
        run: |
          bencher run --adapter rust_gungraun --err "cargo bench --bench ${{ matrix.bench }}"
