name: benchmark
on:
  push:
    branches:
      - master
  pull_request: #TODO: remove after testing
    branches:
      - master

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bench:
          - ct_spawn
    steps:
      - uses: actions/checkout@v5

      - run: sudo apt-get update && sudo apt-get install -y valgrind

      - uses: taiki-e/install-action@cargo-binstall
      - name: Install gungraun-runner
        run: |
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "gungraun").version' |\
            tr -d '"'
          )
          cargo binstall --no-confirm gungraun-runner --version $version

      - name: Download previous benchmark data
        uses: actions/cache@v4
        with:
          path: target/gungraun
          key: ${{ runner.os }}-benchmark-${{ matrix.bench }}

      - name: Run ct benchmarks
        run: cargo bench --bench ${{ matrix.bench }}
