name: benchmark
on:
  push:
    branches:
      - master
  pull_request: #TODO: remove after testing
    branches:
      - master

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bench:
          - ct_spawn
    steps:
      - uses: actions/checkout@v5

      - run: sudo apt-get update && sudo apt-get install -y valgrind

      - uses: taiki-e/install-action@cargo-binstall
      - name: Install gungraun-runner
        run: |
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "gungraun").version' |\
            tr -d '"'
          )
          cargo binstall --no-confirm gungraun-runner --version $version

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run ct benchmarks
        run: cargo bench --bench ${{ matrix.bench }} | tee output.txt

      # - name: Store benchmark result
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     tool: "cargo"
      #     output-file-path: output.txt
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     auto-push: true
      #     fail-on-alert: true
      #     alert-threshold: '150%' #TODO: TBD
      #     comment-on-alert: true
      #     #TODO: alert tokio maintainers?
