name: Stress Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  stess-test:
    name: Stress Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stress-test:
          - simple_echo_tcp
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable

      - name: Install Valgrind
        run: sudo apt-get install -y valgrind

      # Compiles each of the stress test examples.
      - name: Compile stress test examples
        run: cargo build -p stress-test --release --example ${{ matrix.stress-test }}

      # Runs each of the examples using Valgrind. Detects leaks and displays them.
      - name: Run valgrind
        run: valgrind  --leak-check=full --show-leak-kinds=all ./target/release/examples/${{ matrix.stress-test }}
